# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        public: true
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.

    memcached:
        class: Memcached
        calls:
            - [ addServer, [ "%env(SYMFONY__MEMCACHE__HOST)%", "%env(SYMFONY__MEMCACHE__PORT)%" ]]

    ipresence.services.slug:
        class: Ausi\SlugGenerator\SlugGenerator

    ipresence.repository.author:
        class: App\Entity\AuthorRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - App\Entity\Author

    ipresence.repository.quote:
        class: App\Entity\QuoteRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - App\Entity\Quote

    ipresence.command.load_quotes:
        class: App\Command\LoadQuotesCommand
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@ipresence.repository.author'
            - '@ipresence.services.slug'
            - '@kernel'
        tags: ['console.command']

    ipresence.services.quotes_handler:
        class: App\Services\QuotesHandler
        arguments:
            - '@ipresence.repository.quote'
            - '@memcached'
            - 100

    ipresence.usecase.get_quotes:
        class: App\Usecase\GetQuotes
        arguments:
            - '@ipresence.services.quotes_handler'
            - '@ipresence.repository.author'
            - 10
